package com.wipro.basic;

public class EX3 {
    public static void main(String[] args) {
        String field1 = "";
        String field2 = "";
        String field3 = "";
        String field4 = "";
        String field5 = "";
        String field6 = "";
        String field7 = "";
        String field8 = "";
        String field9 = "";
        String field10 = "";
        String field11 = "";
        String field12 = "";
        String field13 = "";
        String field14 = "";
        String field15 = "";
        String field16 = "";
        String field17 = "";
        String field18 = "";
        String field19 = "";
        String field20 = "";
        String field21 = "";
        String field22 = "";
        String field23 = "";
        String field24 = "";
        String field25 = "";
        String field26 = "";
        String field27 = "";
        String field28 = "";
        String field29 = "";
        String field30 = "";
        String field31 = "";
        String field32 = "";
        String field33 = "";
        String field34 = "";
        String field35 = "";
        String field36 = "";
        String field37 = "";
        String field38 = "";
        String field39 = "";
        String field40 = "";

        System.out.println(field1);
        System.out.println(field2);
        System.out.println(field3);
        System.out.println(field4);
        System.out.println(field5);
        System.out.println(field6);
        System.out.println(field7);
        System.out.println(field8);
        System.out.println(field9);
        System.out.println(field10);
        System.out.println(field11);
        System.out.println(field12);
        System.out.println(field13);
        System.out.println(field14);
        System.out.println(field15);
        System.out.println(field16);
        System.out.println(field17);
        System.out.println(field18);
        System.out.println(field19);
        System.out.println(field20);
        System.out.println(field21);
        System.out.println(field22);
        System.out.println(field23);
        System.out.println(field24);
        System.out.println(field25);
        System.out.println(field26);
        System.out.println(field27);
        System.out.println(field28);
        System.out.println(field29);
        System.out.println(field30);
        System.out.println(field31);
        System.out.println(field32);
        System.out.println(field33);
        System.out.println(field34);
        System.out.println(field35);
        System.out.println(field36);
        System.out.println(field37);
        System.out.println(field38);
        System.out.println(field39);
        System.out.println(field40);
    }
}
